name: dbt CI/CD

# Trigger workflow on push or pull request to main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dbt-run:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dbt and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dbt-snowflake  # or dbt-core + your adapter

    - name: Configure profiles.yml
      shell: pwsh
      run: |
        # Create the .dbt directory
        New-Item -ItemType Directory -Path "$env:USERPROFILE\.dbt" -Force

        # Define the profiles.yml content
        $profileContent = @"
    my_dbt_project:
      outputs:
        dev:
          type: snowflake
          account: your_snowflake_account
        user: your_snowflake_user
        password: your_snowflake_password
        role: your_snowflake_role
        warehouse: your_snowflake_warehouse
        threads: 4    
      target: dev
"@

      # Write the content to profiles.yml
      $profilePath = "$env:USERPROFILE\.dbt\profiles.yml"
      $profileContent | Out-File -FilePath $profilePath -Encoding ascii


    - name: dbt deps
      run: dbt deps

    - name: dbt run
      run: dbt run

    - name: dbt test
      run: dbt test