name: dbt CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dbt-run:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dbt and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-snowflake

      - name: Configure profiles.yml
        shell: pwsh
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        run: |
          # Create the .dbt directory
          New-Item -ItemType Directory -Path "$env:USERPROFILE\.dbt" -Force

          # Define the profiles.yml content
          $profileContent = @"
          my_dbt_project:
            outputs:
              dev:
                type: snowflake
                account: $env:SNOWFLAKE_ACCOUNT
                user: $env:SNOWFLAKE_USER
                password: $env:SNOWFLAKE_PASSWORD
                role: $env:SNOWFLAKE_ROLE
                warehouse: $env:SNOWFLAKE_WAREHOUSE
                database: $env:SNOWFLAKE_DATABASE
                schema: $env:SNOWFLAKE_SCHEMA
                threads: 4
            target: dev
          "@

          # Write the content to profiles.yml
          $profilePath = "$env:USERPROFILE\.dbt\profiles.yml"
          $profileContent | Out-File -FilePath $profilePath -Encoding ascii

      - name: dbt deps (development deps)
        run: dbt deps  --development

      - name: dbt run (development run)
        run: dbt run  --development

      - name: dbt test (development tests)
        run: dbt test  --development
